

#spring:
#  datasource:
#    username: springboot
#    password: RZjDLTbMS34F8amJ
#    url: jdbc:mysql://locahost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver

#mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
#  type-aliases-package: com.needayeah.elastic.mapper

