spring:
  profiles:
    active: fat
  servlet:
    multipart:
      #设置单个文件大小
      max-file-size: 10MB
      # 设置单次请求文件的总大小
      max-request-size: 50MB
  application:
    name: elastic

server:
  port: 8088


#showSql
#logging:
#  level:
#    com:
#      needayeah:
#          elastic:
#            mapper: debug