spring:
  profiles:
    active: dev
server:
  port: 8088

#showSql
#logging:
#  level:
#    com:
#      needayeah:
#          elastic:
#            mapper: debug

elasticsearch:
  restHighLevel:
    Client:
      hosts: 127.0.0.1:9200
aliYun:
  sms:
    accessKeyId: 参见阿里云短信服务控制台
    accessKeySecret: 参见阿里云短信服务控制台
    signName: 参见阿里云短信服务控制台