

#spring:
#  datasource:
#    username: springboot
#    password: RZjDLTbMS34F8amJ
#    url: jdbc:mysql://locahost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver

#mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
#  type-aliases-package: com.needayeah.elastic.mapper

# elasticsearch搭建
elasticsearch:
  restHighLevel:
    Client:
      hosts: xxx:9200


# 阿里云短信
aliYun:
  sms:
    accessKeyId: xxx
    accessKeySecret: xxx
    signName: xxx

  # 阿里云存储
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    accessKeyId: xxx
    accessKeySecret: xxx
    bucketName: xxx
    filePath: temp/dev/

# redis集群
redis:
  nodes: xxx:6379
  password: xxx