#spring:
#  datasource:
#    username: springboot
#    password: RZjDLTbMS34F8amJ
#    url: jdbc:mysql://locahost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver

#mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
#  type-aliases-package: com.needayeah.elastic.mapper

# elasticsearch搭建
elasticsearch:
  restHighLevel:
    Client:
      hosts: 127.0.0.1:9200


# 阿里云短信
aliYun:
  sms:
    accessKeyId: xxxx
    accessKeySecret: xxxxxxxxxxx
    signName: xxxx

  # 阿里云存储
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    accessKeyId: xxxxxxxx
    accessKeySecret: xxxxxxxxxxx
    bucketName: xxxxx
    filePath: temp/dev/

# redis集群
redis:
  nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
  password: 7621024a


spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/sys?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    addresses: 127.0.0.1:5672, 127.0.0.1:5673, 127.0.0.1:5674
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false
      direct:
        acknowledge-mode: manual
    publisher-confirm-type: correlated
    template:
      mandatory: true

xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://127.0.0.1:8080/xxl-job-admin
    ### xxl-job, access token
    accessToken:
    executor:
      appname: elastic
      ### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      address:
      ### xxl-job executor server-info
      ip:
      port: 9998
      ### xxl-job executor log-path
      logpath: /data/applogs/xxl-job/jobhandler
      ### xxl-job executor log-retention-days
      logretentiondays: 30